version: "3"

networks:
  tx-net:
    external: false

services:
  dcs:
    build:
      context: .
      args:
        - DOOR43_PREVIEW_PORT=${DOOR43_PREVIEW_PORT-5556}
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    ports:
      - "${DCS_PORT-5555}:80"
      - "222:22"
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - tx-net

